name: CD
on:
  push:
    branches:
      - next
  workflow_dispatch:

jobs:
  release-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build
        run: |
          ls ./src
          npm install -g pkg
          npm install tsc
          npm install
          npm run build
          pkg ./dist/src/index.js
      - name: Null Action
        run: echo *** hello ***
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
