name: CD
on:
  push:
    branches:
      - next
  workflow_dispatch:

jobs:
  release-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install
        run: |
          npm install -g pkg
          npm install -g typescript
          npm install
      - name: Release Package
        run: |
          make release
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Set SHA
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./releases/gac-macos-x64.tar.gz | awk '{printf $1}')"
